CREATE TABLE dashboard_news
(
	id INT NOT NULL AUTO_INCREMENT,
	`title` CHAR(255) DEFAULT NULL,
	author INT DEFAULT NULL,
	link CHAR(255) DEFAULT NULL,
	story TEXT,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);
